# -*- coding: utf-8 -*-
"""players bundesliga webscraping.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_06oIQ7w3OdaXYrfqsydMdR098mNk0gk

# **استيراد المكتبات**
"""

from bs4 import BeautifulSoup
import requests
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

"""# **استيراد الموقع واستخراد البيانات**"""

webpage = requests.get("https://www.bundesliga.com/en/bundesliga/player")
soup = BeautifulSoup(webpage.content, "html.parser")
"https://www.bundesliga.com/en/bundesliga/player"

"""# **تحديد الكلاس الذي تريد استيراده**"""

names_column=soup.find_all(attrs={"class":"names"})
names_list=[]

playerNumber_column=soup.find_all(attrs={"class":"playerNumber"})
playerNumber_list=[]

"""# ***مرحلة المعالجة (Processing / Data Processing)***"""

for x in names_column[1:]:
    names_list.append(x.get_text())

for x in playerNumber_column[1:]:
    playerNumber_list.append(x.get_text())

"""***طباعة النتائج***"""

print(names_list)
print(playerNumber_list)

"""# ***وضعها في ملف csv***"""

df = pd.DataFrame({
    "names"  : names_list
  , "playerNumber" : playerNumber_list
})
df.to_csv("players_list.csv", index=False, encoding="utf-8")

print("players_list.csv ")