# -*- coding: utf-8 -*-
"""ghayawebscrapingCACAORATING.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W4nQGctwrg8guNfSN8FoSeWmGvObhHAa

# **استيراد المكتبات**
"""

from bs4 import BeautifulSoup
import requests
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

"""# **استيراد الموقع واستخراد البيانات**"""

webpage = requests.get("https://content.codecademy.com/courses/beautifulsoup/cacao/index.html")
soup = BeautifulSoup(webpage.content, "html.parser")
"https://content.codecademy.com/courses/beautifulsoup/cacao/index.html"

"""# **تحديد الكلاس الذي تريد استيراده**"""

Rating_column=soup.find_all(attrs={"class":"Rating"})
Rating_list=[]

ReviewDate_column=soup.find_all(attrs={"class":"ReviewDate"})
ReviewDate_list=[]


REF_column=soup.find_all(attrs={"class":"REF"})
REF_list=[]

Origin_column=soup.find_all(attrs={"class":"Origin"})
Origin_list=[]

"""# ***مرحلة المعالجة (Processing / Data Processing)***"""

for x in Rating_column[1:]:
    Rating_list.append(float(x.get_text()))

for x in ReviewDate_column[1:]:
    ReviewDate_list.append(x.get_text())

for x in REF_column[1:]:
    REF_list.append(float(x.get_text()))


for x in Origin_column[1:]:
    Origin_list.append(x.get_text())

"""***طباعة النتائج***"""

print(Rating_list)
print(REF_list)
print(ReviewDate_list)
print(Origin_list)

"""# ***وضعها في ملف csv***"""

df = pd.DataFrame({
    "Rating" : Rating_list
    ,"REF" : REF_list
    ,"ReviewDate" : ReviewDate_list
    ,"Origin" : Origin_list
})
df.to_csv("RatingANDrefANDReviewDateANDorigin_list.csv", index=False, encoding="utf-8")

print("RatingANDrefANDReviewDateANDorigin_list.csv ")